services:
  ael-rule:
    container_name: ael-rule
    image: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=rule.ael.ovh
      - NGINX_PORT=80
    volumes:
      - /var/www/html/ael-rules:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ael-rule.tls=true"
      - "traefik.http.routers.ael-rule.entrypoints=websecure"
      - "traefik.http.routers.ael-rule.rule=Host(`rule.ael.ovh`)"
      - "traefik.http.routers.ael-rule.tls.domains[0].main=rule.ael.ovh"
      - "traefik.http.routers.ael-rule.tls.certresolver=myresolver"
      - "traefik.http.services.ael-rule.loadbalancer.server.port=80"


networks:
  prestashop_network:
  proxy:
    external: true # utilise le network externe utilisé par Traefik