version: '3'
services:
  mysql:
    container_name: mysql-ps
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_SERVER: mysql-ps
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    volumes:
      - /var/www/modules_checkout:/var/www/html/modules/ps_checkout
    networks:
      - prestashop_network
      - proxy
    ports:
     - 8082:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prestashop.tls=true"
      - "traefik.http.routers.prestashop.entrypoints=websecure"
      - "traefik.http.routers.prestashop.rule=Host(`ps.ael.ovh`)"
      - "traefik.http.routers.prestashop.tls.certresolver=myresolver"
      - "traefik.http.services.prestashop.loadbalancer.server.port=80"

networks:
  prestashop_network:
  proxy:
    external: true # utilise le network externe utilisé par Traefik