version: '3'
services:
  bo-sdk:
    container_name: bo-sdk
    image: vue-bo
    restart: unless-stopped
    ports:
      - 8084:3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sample-http.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`bo-sdk.ael.ovh`)"
      - "traefik.http.routers.sample-http.service=sample-http"
      - "traefik.http.services.sample-http.loadBalancer.server.port=80"
networks:
  prestashop_network:
  proxy:
    external: true # utilise le network externe utilisé par Traefik