services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    entrypoint:
      - /bin/sh
      - /docker-entrypoint-ngrok.sh
    ports:
      - "4040:4040"
    volumes:
      - ./docker-entrypoint-ngrok.sh:/docker-entrypoint-ngrok.sh:ro

networks:
  proxy:
    external: true
